//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


//INSTANT C# NOTE: Formerly VB project-level imports:
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Diagnostics;
using System.Windows.Forms;

namespace Crowbar
{
	namespace Properties
	{

		//This class was auto-generated by the StronglyTypedResourceBuilder
		//class via a tool like ResGen or Visual Studio.
		//To add or remove a member, edit your .ResX file then rerun ResGen
		//with the /str option, or rebuild your VS project.
		///<summary>
		///  A strongly-typed resource class, for looking up localized strings, etc.
		///</summary>
		[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
		internal static class Resources
		{

			private static System.Resources.ResourceManager resourceMan;

			private static System.Globalization.CultureInfo resourceCulture;

			///<summary>
			///  Returns the cached ResourceManager instance used by this class.
			///</summary>
			[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
			internal static System.Resources.ResourceManager ResourceManager
			{
				get
				{
					if (object.ReferenceEquals(resourceMan, null))
					{
						System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Crowbar.Properties.Resources", typeof(Resources).Assembly);
						resourceMan = temp;
					}
					return resourceMan;
				}
			}

			///<summary>
			///  Overrides the current thread's CurrentUICulture property for all
			///  resource lookups using this strongly typed resource class.
			///</summary>
			[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
			internal static System.Globalization.CultureInfo Culture
			{
				get
				{
					return resourceCulture;
				}
				set
				{
					resourceCulture = value;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap _26_Grey_PayPal_Pill_Button
			{
				get
				{
					object obj = ResourceManager.GetObject("_26_Grey_PayPal_Pill_Button", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized string similar to http://steamcommunity.com/id/zeqmacaw.
			///</summary>
			internal static string About_AuthorLink
			{
				get
				{
					return ResourceManager.GetString("About_AuthorLink", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized string similar to Goto Steam Group.
			///</summary>
			internal static string About_GotoSteamGroupText
			{
				get
				{
					return ResourceManager.GetString("About_GotoSteamGroupText", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized string similar to Goto Steam Profile.
			///</summary>
			internal static string About_GotoSteamProfileText
			{
				get
				{
					return ResourceManager.GetString("About_GotoSteamProfileText", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized string similar to http://paypal.me/zeqmacaw.
			///</summary>
			internal static string About_PayPalLink
			{
				get
				{
					return ResourceManager.GetString("About_PayPalLink", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized string similar to GoldSource and Source Engine Modding Toolset:
			///* Decompiler of MDL and related files.
			///* Compiler interface to StudioMDL.exe tool.
			///* Model viewer interface to Half-Life Model Viewer tool.
			///* Unpacker of Fairy Tale Busters APK, Tactical Intervention FPX, Garry&apos;s Mod GMA, Vampire: The Masquerade - Bloodlines VPK files, and Source-engine VPK files.
			///* Packer interface to Garry&apos;s Mod GMA and Source-engine VPK packer tools.
			///* Downloader of Workshop items from any Steam game that allows public downloads.
			///* Pub [rest of string was truncated]&quot;;.
			///</summary>
			internal static string About_ProductDescription
			{
				get
				{
					return ResourceManager.GetString("About_ProductDescription", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized string similar to http://steamcommunity.com/groups/CrowbarTool.
			///</summary>
			internal static string About_ProductLink
			{
				get
				{
					return ResourceManager.GetString("About_ProductLink", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized string similar to https://steamcommunity.com/groups/CrowbarTool/discussions/1/.
			///</summary>
			internal static string BugReportLink
			{
				get
				{
					return ResourceManager.GetString("BugReportLink", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized string similar to https://steamcommunity.com/groups/CrowbarTool/discussions/1/.
			///</summary>
			internal static string BugReportLink1
			{
				get
				{
					return ResourceManager.GetString("BugReportLink1", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap CancelRefresh
			{
				get
				{
					object obj = ResourceManager.GetObject("CancelRefresh", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap CancelSearch
			{
				get
				{
					object obj = ResourceManager.GetObject("CancelSearch", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
			///</summary>
			internal static System.Drawing.Icon crowbar_icon
			{
				get
				{
					object obj = ResourceManager.GetObject("crowbar_icon", resourceCulture);
					return (System.Drawing.Icon)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap crowbar_icon_large
			{
				get
				{
					object obj = ResourceManager.GetObject("crowbar_icon_large", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
			///&lt;AppSettings xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
			///  &lt;GameSetups&gt;
			///    &lt;GameSetup&gt;
			///      &lt;GameName&gt;Age of Chivalry&lt;/GameName&gt;
			///      &lt;GameEngine&gt;Source&lt;/GameEngine&gt;
			///      &lt;GamePathFileName&gt;&amp;lt;library1&amp;gt;\steamapps\common\Source SDK Base 2007\ageofchivalry\gameinfo.txt&lt;/GamePathFileName&gt;
			///      &lt;GameAppPathFileName&gt;&amp;lt;library1&amp;gt;\steamapps\common\Source SDK Base 2007\hl2.exe&lt;/GameAppPathFileName&gt;
			///    [rest of string was truncated]&quot;;.
			///</summary>
			internal static string Crowbar_Settings
			{
				get
				{
					return ResourceManager.GetString("Crowbar_Settings", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap CrowbarGuideBanner
			{
				get
				{
					object obj = ResourceManager.GetObject("CrowbarGuideBanner", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Byte[].
			///</summary>
			internal static byte[] CrowbarLauncher
			{
				get
				{
					object obj = ResourceManager.GetObject("CrowbarLauncher", resourceCulture);
					return (byte[])obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Byte[].
			///</summary>
			internal static byte[] CrowbarSteamPipe
			{
				get
				{
					object obj = ResourceManager.GetObject("CrowbarSteamPipe", resourceCulture);
					return (byte[])obj;
				}
			}

			///<summary>
			///  Looks up a localized string similar to decompile-ANI.txt.
			///</summary>
			internal static string Decompile_DebugAniFileNameSuffix
			{
				get
				{
					return ResourceManager.GetString("Decompile_DebugAniFileNameSuffix", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized string similar to decompile-MDL.txt.
			///</summary>
			internal static string Decompile_DebugMdlFileNameSuffix
			{
				get
				{
					return ResourceManager.GetString("Decompile_DebugMdlFileNameSuffix", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized string similar to decompile-PHY.txt.
			///</summary>
			internal static string Decompile_DebugPhyFileNameSuffix
			{
				get
				{
					return ResourceManager.GetString("Decompile_DebugPhyFileNameSuffix", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized string similar to decompile-SequenceGroupMDL.txt.
			///</summary>
			internal static string Decompile_DebugSequenceGroupMDLFileNameSuffix
			{
				get
				{
					return ResourceManager.GetString("Decompile_DebugSequenceGroupMDLFileNameSuffix", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized string similar to decompile-TextureMDL.txt.
			///</summary>
			internal static string Decompile_DebugTextureMDLFileNameSuffix
			{
				get
				{
					return ResourceManager.GetString("Decompile_DebugTextureMDLFileNameSuffix", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized string similar to decompile-VTX.txt.
			///</summary>
			internal static string Decompile_DebugVtxFileNameSuffix
			{
				get
				{
					return ResourceManager.GetString("Decompile_DebugVtxFileNameSuffix", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized string similar to decompile-VVD.txt.
			///</summary>
			internal static string Decompile_DebugVvdFileNameSuffix
			{
				get
				{
					return ResourceManager.GetString("Decompile_DebugVvdFileNameSuffix", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized string similar to decompile-log.txt.
			///</summary>
			internal static string Decompile_LogFileNameSuffix
			{
				get
				{
					return ResourceManager.GetString("Decompile_LogFileNameSuffix", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap EnterArrow
			{
				get
				{
					object obj = ResourceManager.GetObject("EnterArrow", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized string similar to Possible causes: The game&apos;s SDK or Authoring Tools has not been installed (usually via Steam Library Tools) or the path given to Crowbar (via Set Up Games button) is incorrect..
			///</summary>
			internal static string ErrorMessageSDKMissingCause
			{
				get
				{
					return ResourceManager.GetString("ErrorMessageSDKMissingCause", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap Find
			{
				get
				{
					object obj = ResourceManager.GetObject("Find", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap FindNext
			{
				get
				{
					object obj = ResourceManager.GetObject("FindNext", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap FindPrevious
			{
				get
				{
					object obj = ResourceManager.GetObject("FindPrevious", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized string similar to http://steamcommunity.com/sharedfiles/filedetails/?id=791755353.
			///</summary>
			internal static string Help_CrowbarGuideLink
			{
				get
				{
					return ResourceManager.GetString("Help_CrowbarGuideLink", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized string similar to https://steamcommunity.com/sharedfiles/workshoplegalagreement.
			///</summary>
			internal static string Link_SteamSubscriberAgreement
			{
				get
				{
					return ResourceManager.GetString("Link_SteamSubscriberAgreement", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Byte[].
			///</summary>
			internal static byte[] lzma
			{
				get
				{
					object obj = ResourceManager.GetObject("lzma", resourceCulture);
					return (byte[])obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap macaw
			{
				get
				{
					object obj = ResourceManager.GetObject("macaw", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap Refresh
			{
				get
				{
					object obj = ResourceManager.GetObject("Refresh", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Byte[].
			///</summary>
			internal static byte[] SevenZr
			{
				get
				{
					object obj = ResourceManager.GetObject("SevenZr", resourceCulture);
					return (byte[])obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Byte[].
			///</summary>
			internal static byte[] steam_api
			{
				get
				{
					object obj = ResourceManager.GetObject("steam_api", resourceCulture);
					return (byte[])obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Byte[].
			///</summary>
			internal static byte[] Steamworks_NET
			{
				get
				{
					object obj = ResourceManager.GetObject("Steamworks_NET", resourceCulture);
					return (byte[])obj;
				}
			}

			///<summary>
			///  Looks up a localized string similar to unpack-log.txt.
			///</summary>
			internal static string Unpack_LogFileNameSuffix
			{
				get
				{
					return ResourceManager.GetString("Unpack_LogFileNameSuffix", resourceCulture);
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap WordWrap
			{
				get
				{
					object obj = ResourceManager.GetObject("WordWrap", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap WordWrapOff
			{
				get
				{
					object obj = ResourceManager.GetObject("WordWrapOff", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}
		}
	}

}