//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowbar.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowbar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _16621925 {
            get {
                object obj = ResourceManager.GetObject("16621925", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _26_Grey_PayPal_Pill_Button {
            get {
                object obj = ResourceManager.GetObject("_26_Grey_PayPal_Pill_Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://steamcommunity.com/id/zeqmacaw.
        /// </summary>
        internal static string About_AuthorLink {
            get {
                return ResourceManager.GetString("About_AuthorLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Goto Steam Group.
        /// </summary>
        internal static string About_GotoSteamGroupText {
            get {
                return ResourceManager.GetString("About_GotoSteamGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Goto Steam Profile.
        /// </summary>
        internal static string About_GotoSteamProfileText {
            get {
                return ResourceManager.GetString("About_GotoSteamProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://steamcommunity.com/profiles/76561198121485860.
        /// </summary>
        internal static string About_ModifiedAuthorSteam {
            get {
                return ResourceManager.GetString("About_ModifiedAuthorSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://github.com/DeadZoneLuna/Crowbar-CSharp-Test.
        /// </summary>
        internal static string About_ModifiedGithub {
            get {
                return ResourceManager.GetString("About_ModifiedGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://paypal.me/zeqmacaw.
        /// </summary>
        internal static string About_PayPalLink {
            get {
                return ResourceManager.GetString("About_PayPalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GoldSource and Source Engine Modding Toolset:
        ///* Decompiler of MDL and related files.
        ///* Compiler interface to StudioMDL.exe tool.
        ///* Model viewer interface to Half-Life Model Viewer tool.
        ///* Unpacker of Fairy Tale Busters APK, Tactical Intervention FPX, Garry&apos;s Mod GMA, Vampire: The Masquerade - Bloodlines VPK files, and Source-engine VPK files.
        ///* Packer interface to Garry&apos;s Mod GMA and Source-engine VPK packer tools.
        ///* Downloader of Workshop items from any Steam game that allows public downloads.
        ///* Publisher  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string About_ProductDescription {
            get {
                return ResourceManager.GetString("About_ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://steamcommunity.com/groups/CrowbarTool.
        /// </summary>
        internal static string About_ProductLink {
            get {
                return ResourceManager.GetString("About_ProductLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://steamcommunity.com/groups/CrowbarTool/discussions/1/.
        /// </summary>
        internal static string BugReportLink {
            get {
                return ResourceManager.GetString("BugReportLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://steamcommunity.com/groups/CrowbarTool/discussions/1/.
        /// </summary>
        internal static string BugReportLink1 {
            get {
                return ResourceManager.GetString("BugReportLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CancelRefresh {
            get {
                object obj = ResourceManager.GetObject("CancelRefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CancelSearch {
            get {
                object obj = ResourceManager.GetObject("CancelSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon crowbar_icon {
            get {
                object obj = ResourceManager.GetObject("crowbar_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crowbar_icon_large {
            get {
                object obj = ResourceManager.GetObject("crowbar_icon_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;AppSettings xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;GameSetups&gt;
        ///    &lt;GameSetup&gt;
        ///      &lt;GameName&gt;Age of Chivalry&lt;/GameName&gt;
        ///      &lt;GameEngine&gt;Source&lt;/GameEngine&gt;
        ///      &lt;GamePathFileName&gt;&amp;lt;library1&amp;gt;\steamapps\common\Source SDK Base 2007\ageofchivalry\gameinfo.txt&lt;/GamePathFileName&gt;
        ///      &lt;GameAppPathFileName&gt;&amp;lt;library1&amp;gt;\steamapps\common\Source SDK Base 2007\hl2.exe&lt;/GameAppPathFileName&gt;
        ///      &lt;Game [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Crowbar_Settings {
            get {
                return ResourceManager.GetString("Crowbar_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CrowbarGuideBanner {
            get {
                object obj = ResourceManager.GetObject("CrowbarGuideBanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CrowbarLauncher {
            get {
                object obj = ResourceManager.GetObject("CrowbarLauncher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CrowbarSteamPipe {
            get {
                object obj = ResourceManager.GetObject("CrowbarSteamPipe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на decompile-ANI.txt.
        /// </summary>
        internal static string Decompile_DebugAniFileNameSuffix {
            get {
                return ResourceManager.GetString("Decompile_DebugAniFileNameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на decompile-MDL.txt.
        /// </summary>
        internal static string Decompile_DebugMdlFileNameSuffix {
            get {
                return ResourceManager.GetString("Decompile_DebugMdlFileNameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на decompile-PHY.txt.
        /// </summary>
        internal static string Decompile_DebugPhyFileNameSuffix {
            get {
                return ResourceManager.GetString("Decompile_DebugPhyFileNameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на decompile-SequenceGroupMDL.txt.
        /// </summary>
        internal static string Decompile_DebugSequenceGroupMDLFileNameSuffix {
            get {
                return ResourceManager.GetString("Decompile_DebugSequenceGroupMDLFileNameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на decompile-TextureMDL.txt.
        /// </summary>
        internal static string Decompile_DebugTextureMDLFileNameSuffix {
            get {
                return ResourceManager.GetString("Decompile_DebugTextureMDLFileNameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на decompile-VTX.txt.
        /// </summary>
        internal static string Decompile_DebugVtxFileNameSuffix {
            get {
                return ResourceManager.GetString("Decompile_DebugVtxFileNameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на decompile-VVD.txt.
        /// </summary>
        internal static string Decompile_DebugVvdFileNameSuffix {
            get {
                return ResourceManager.GetString("Decompile_DebugVvdFileNameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на decompile-log.txt.
        /// </summary>
        internal static string Decompile_LogFileNameSuffix {
            get {
                return ResourceManager.GetString("Decompile_LogFileNameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EnterArrow {
            get {
                object obj = ResourceManager.GetObject("EnterArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Possible causes: The game&apos;s SDK or Authoring Tools has not been installed (usually via Steam Library Tools) or the path given to Crowbar (via Set Up Games button) is incorrect..
        /// </summary>
        internal static string ErrorMessageSDKMissingCause {
            get {
                return ResourceManager.GetString("ErrorMessageSDKMissingCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Find {
            get {
                object obj = ResourceManager.GetObject("Find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindNext {
            get {
                object obj = ResourceManager.GetObject("FindNext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindPrevious {
            get {
                object obj = ResourceManager.GetObject("FindPrevious", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://steamcommunity.com/sharedfiles/filedetails/?id=791755353.
        /// </summary>
        internal static string Help_CrowbarGuideLink {
            get {
                return ResourceManager.GetString("Help_CrowbarGuideLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://steamcommunity.com/sharedfiles/workshoplegalagreement.
        /// </summary>
        internal static string Link_SteamSubscriberAgreement {
            get {
                return ResourceManager.GetString("Link_SteamSubscriberAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] lzma {
            get {
                object obj = ResourceManager.GetObject("lzma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap macaw {
            get {
                object obj = ResourceManager.GetObject("macaw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SevenZr {
            get {
                object obj = ResourceManager.GetObject("SevenZr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] steam_api {
            get {
                object obj = ResourceManager.GetObject("steam_api", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Steamworks_NET {
            get {
                object obj = ResourceManager.GetObject("Steamworks_NET", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на unpack-log.txt.
        /// </summary>
        internal static string Unpack_LogFileNameSuffix {
            get {
                return ResourceManager.GetString("Unpack_LogFileNameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WordWrap {
            get {
                object obj = ResourceManager.GetObject("WordWrap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WordWrapOff {
            get {
                object obj = ResourceManager.GetObject("WordWrapOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
